version: '2'
services:
  postgresql:
    image: releases-docker.jfrog.io/postgres:13.4-alpine
    container_name: artifactory-db
    environment:
     - POSTGRES_DB=artifactory
     # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
     - POSTGRES_USER=artifactory
     - POSTGRES_PASSWORD=password
    #volumes:
    # - /var/artifactory/home-docker-compose/postgresql:/var/lib/postgresql/data
    # Restart automatically on crash or reboot, unless already stopped.
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:7.37.14
    container_name: artifactory-server
    ports:
     # Exposing on localhost port.
     - 127.0.0.1:18081:8081
     - 127.0.0.1:18082:8082
     # Exposing SSH port on all interfaces.
     - "1339:1339"
    depends_on:
     - postgresql
    volumes:
     # Mount the persistent Artifactory home.
     - ./artifactory:/var/opt/jfrog/artifactory
     # Bake in the DeltekUSRoot certificate to make LDAP authentication work.
     # (Otherwise the LDAPS call will fail authentication.)
     ##- /var/artifactory/certs:/opt/jfrog/artifactory/var/etc/security/keys/trusted
     # Pick up timezone from host.
     - /etc/localtime:/etc/localtime:ro
    #environment:
     # Add extra Java options by uncommenting the following line
     #- EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    # Restart automatically on crash or reboot, unless already stopped.
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
